spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: 9227b9Ec
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: zurabi.papiashvili.2@gmail.com
    password: yyja piln hioy gcgo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

application:
  security:
    jwt:
      secret-key: DA9577D9BD398FA58AC98A32BC38CDA9577D9BD398FA58AC98A32BC38CDA9577D9BD398FA58AC98A32BC38C
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088

# swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persist-authorization: true
    enabled: true
