spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
  mailing:
    frontend:
      activation-url: ${FRONTEND_ACTIVATION_URL}
  cors:
    allowed-origins: http://localhost:4200, http://localhost:8080,
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allowed-headers: Authorization, Content-Type, X-Requested-With, X-XSRF-TOKEN
    exposed-headers: Authorization, Content-Type, X-Requested-With, X-XSRF-TOKEN
    allow-credentials: true
    max-age: 3600
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: ${SERVER_PORT}

# swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persist-authorization: true
    enabled: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY_ID}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false
