spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY_ID}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false

application:
  bucket:
    name: ${AWS_S3_BUCKET_NAME}
